version: "2"
volumes:
  web_cache:
services:
  nginx:                        # Nginx web server
    extends: { file: nginx.yml, service: nginx }
    volumes:
      - web_cache:/var/cache/nginx
      - ${TRAMBAR_MEDIA_FOLDER}:/var/cache/media:z
    depends_on:
      - data_server
      - admin_data_server
      - media_server
      - event_notifier
      - www_handler
<% if (gitlab) { %>
      - gitlab
<% } %>
<% if (wordpress) { %>
      - wordpress
<% } %>
  postgres:                     # PostgreSQL database manager
    extends: { file: postgres.yml, service: postgres }
    ports:
      - 5432:5432
  schema_manager:               # Database schema manager (Node.js)
    extends:
      file: node.yml
      service: node
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_ROOT_PASSWORD}
      - DATABASE_ADMIN_PASSWORD=${TRAMBAR_DATABASE_ADMIN_PASSWORD}
      - DATABASE_CLIENT_PASSWORD=${TRAMBAR_DATABASE_CLIENT_PASSWORD}
      - DATABASE_AUTH_PASSWORD=${TRAMBAR_DATABASE_AUTH_PASSWORD}
    command: [ nodemon, --experimental-modules, schema-manager.mjs ]
    depends_on:
      - postgres
  webdav_server:                # WebDAV server (Node.js)
    extends: { file: node.yml, service: node }
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_ROOT_PASSWORD}
    command: [ nodemon, --experimental-modules, webdav-server.mjs ]
    depends_on:
      - postgres
  www_handler:                  # Web page handler (Node.js)
    extends: { file: node.yml, service: node }
    volumes:
      - web_cache:/var/cache/nginx
    command: [ nodemon, --experimental-modules, www-handler.mjs ]
    depends_on:
      - postgres
  data_server:                  # Data server (Node.js)
    extends: { file: node.yml, service: node }
    command: [ nodemon, --experimental-modules, data-server.mjs ]
    depends_on:
      - postgres
  admin_data_server:            # Admin data server (Node.js)
    extends: { file: node.yml, service: node }
    environment:
      - POSTGRES_USER=admin_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_ADMIN_PASSWORD}
    command: [ nodemon, --experimental-modules, data-server.mjs ]
    depends_on:
      - postgres
  session_manager:              # Authentication manager (Node.js)
    extends: { file: node.yml, service: node }
    volumes:
      - ${TRAMBAR_HTPASSWD_FOLDER}:/etc/trambar
    environment:
      - POSTGRES_USER=auth_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_AUTH_PASSWORD}
      - HTPASSWD_PATH=/etc/trambar/${TRAMBAR_HTPASSWD_NAME}
    command: [ nodemon, --experimental-modules, session-manager.mjs ]
    depends_on:
      - postgres
  media_server:                 # Media server (Node.js)
    extends: { file: node.yml, service: node }
    volumes:
      - ${TRAMBAR_MEDIA_FOLDER}:/var/cache/media
    command: [ nodemon, --experimental-modules, media-server.mjs ]
    depends_on:
      - postgres
  event_notifier:               # WebSocket Notifier (Node.js)
    extends: { file: node.yml, service: node }
    command: [ nodemon, --experimental-modules, event-notifier.mjs ]
    depends_on:
      - postgres
  live_data_invalidator:        # Live Data Invalidator (Node.js)
    extends: { file: node.yml, service: node }
    command: [ nodemon, --experimental-modules, live-data-invalidator.mjs ]
    depends_on:
      - postgres
  live_data_updater:            # Live Data Updater (Node.js)
    extends: { file: node.yml, service: node }
    command: [ nodemon, --experimental-modules, live-data-updater.mjs ]
    depends_on:
      - postgres
  gitlab_adapter:               # GitLab Adapter (Node.js)
    extends: { file: node.yml, service: node }
    environment:
      - POSTGRES_USER=admin_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_ADMIN_PASSWORD}
    command: [ nodemon, --experimental-modules, gitlab-adapter.mjs ]
    depends_on:
      - postgres
<% if (gitlab) { %>
  gitlab:                       # GitLab
    extends: { file: gitlab.yml, service: gitlab }
<% } %>
<% if (wordpress) { %>
  wordpress:                    # WordPress
    extends: { file: wordpress.yml, service: wordpress }
    depends_on:
      - wordpress_db
  wordpress_db:                 # MariaDB
    extends: { file: wordpress.yml, service: wordpress_db }
    ports:
      - 3306:3306
<% } %>
volumes:
  web_cache: {}
  <% for (var i = 0; i < volumes.length; i++) { %>
  <%= volumes[i] %>: {}
  <% } %>
