version: "2"
services:
  node:
    image: trambar/trambar-node-dev:${TRAMBAR_BUILD}
    volumes:
      - ${TRAMBAR_SOURCE_FOLDER}/admin/www:/opt/trambar/admin/www
      - ${TRAMBAR_SOURCE_FOLDER}/backend/src:/opt/trambar/backend/src
      - ${TRAMBAR_SOURCE_FOLDER}/backend/media:/opt/trambar/backend/media
      - ${TRAMBAR_SOURCE_FOLDER}/client/www:/opt/trambar/client/www
      - ${TRAMBAR_SOURCE_FOLDER}/common/src:/opt/trambar/backend/src/lib/common
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=client_role
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_CLIENT_PASSWORD}
    restart: ${TRAMBAR_RESTART}
