version: "2"
services:
  postgres:
    image: trambar/trambar-postgres
    ports:
      - 5432:5432
    volumes:
      - ${TRAMBAR_DATABASE_FOLDER}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${TRAMBAR_DATABASE_NAME}
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${TRAMBAR_DATABASE_ROOT_PASSWORD}
