version: "2"
services:
  nginx:
    image: nginx:latest
    ports:
      - ${TRAMBAR_HTTP_PORT}:80
<% if (ssl) { %>
      # set HTTPS port
      - ${TRAMBAR_HTTPS_PORT}:443
<% } %>
    volumes:
      # mount directory containing configuration file
      - ./conf.d:/etc/nginx/conf.d
      # mount directory for media files
      - ${TRAMBAR_MEDIA_FOLDER}:/var/cache/media:z
<% if (ssl) { %>
      # mount directory containing SSL cert and key
      - ${TRAMBAR_SSL_FOLDER}:${TRAMBAR_SSL_FOLDER}
<% } %>
    restart: ${TRAMBAR_RESTART}
